### ISSUE TITLE
JSON and cpuminer

### ISSUE THREAD

**Issue by computeronix** [suda/dashing-mining-agent#11]
How familar are you with the JSON import?   If I provide another JSON type command, lets say from cpuminer-gc3355 (https://github.com/siklon/cpuminer-gc3355/)

Could you assist with decoding the one get command?

Command: {"get":"stats"}\n
Returns JSON formatted dat.  To translate the JSON keys, please refer to cpu-miner.c:66 https://github.com/siklon/cpuminer-gc3355/blob/master/cpu-miner.c

Never really have used JSON and hope it is easy to take their config and just match the data up to the fields :)

**Comment by suda** [comment]
Yeah it's definitely doable. It's best if you send `{"get":"stats"}` command with tool like [Postman](https://chrome.google.com/webstore/detail/postman-rest-client/fdmmgilgnpjigdojojpjoooidkmcomcm?hl=en) and dump the results here. We could figure out how to map them to existing structures.

**Comment by computeronix** [comment]
Ok because the newer version of cpuminer works really well with certain gridseeds (especially with the cool auto-tune feature)

Also will be good to review the JSON because it will give me an idea on pulling the pool information as I may create a widget to hold the pool server currently connected to

Also the socket receive size for the command will need to be 8196.

I had to run the command direct from the machine so here is a telnet view of the command

`minera@gcm-bulldozer ~ $ telnet 127.0.0.1 4028
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
{"get":"stats"}
{"devices":{"ttyACM9":{"chips":[{"autotune":1,"frequency":1028,"accepted":0,"hashrate":0,"rejected":0,"last_share":1425986442,"hw_errors":0,"shares":0},{"autotune":1,"frequency":1028,"accepted":0,"hashrate":0,"rejected":0,"last_share":1425986442,"hw_errors":1,"shares":0},{"autotune":1,"frequency":1028,"accepted":1,"hashrate":86830,"rejected":0,"last_share":1425986953,"hw_errors":0,"shares":384},{"autotune":1,"frequency":1028,"accepted":1,"hashrate":86877,"rejected":0,"last_share":1425986649,"hw_errors":0,"shares":384},{"autotune":1,"frequency":1028,"accepted":0,"hashrate":0,"rejected":0,"last_share":1425986442,"hw_errors":1,"shares":0}],"serial":"6D86437A5157"},"ttyACM8":{"chips":[{"autotune":1,"frequency":1028,"accepted":1,"hashrate":86172,"rejected":0,"last_share":1425986724,"hw_errors":0,"shares":384},{"autotune":1,"frequency":1028,"accepted":1,"hashrate":86748,"rejected":0,"last_share":1425986792,"hw_errors":0,"shares":384},{"autotune":1,"frequency":1028,"accepted":3,"hashrate":86839,"rejected":0,"last_share":1425986938,"hw_errors":0,"shares":1152},{"autotune":1,"frequency":1028,"accepted":4,"hashrate":86817,"rejected":0,"last_share":1425986859,"hw_errors":0,"shares":1536},{"autotune":1,"frequency":1028,"accepted":0,"hashrate":0,"rejected":0,"last_share":1425986442,"hw_errors":0,"shares":0}],"serial":"8D7052755355"},"ttyACM7":{"chips":[{"autotune":1,"frequency":1028,"accepted":2,"hashrate":86875,"rejected":0,"last_share":1425987033,"hw_errors":0,"shares":768},{"autotune":1,"frequency":1028,"accepted":4,"hashrate":86831,"rejected":0,"last_share":1425987075,"hw_errors":0,"shares":1536},{"autotune":1,"frequency":1028,"accepted":3,"hashrate":86834,"rejected":0,"last_share":1425986900,"hw_errors":0,"shares":1152},{"autotune":1,"frequency":1028,"accepted":2,"hashrate":86846,"rejected":0,"last_share":1425986814,"hw_errors":0,"shares":768},{"autotune":1,"frequency":1028,"accepted":3,"hashrate":86786,"rejected":0,"last_share":1425987106,"hw_errors":0,"shares":1152}],"serial":"6D84556F4853"},"ttyACM6":{"chips":[{"autotune":1,"frequency":1028,"accepted":0,"hashrate":0,"rejected":0,"last_share":1425986442,"hw_errors":0,"shares":0},{"autotune":1,"frequency":1028,"accepted":0,"hashrate":0,"rejected":0,"last_share":1425986442,"hw_errors":0,"shares":0},{"autotune":1,"frequency":1028,"accepted":0,"hashrate":0,"rejected":0,"last_share":1425986442,"hw_errors":0,"shares":0},{"autotune":1,"frequency":1028,"accepted":0,"hashrate":0,"rejected":0,"last_share":1425986442,"hw_errors":0,"shares":0},{"autotune":1,"frequency":1028,"accepted":0,"hashrate":0,"rejected":0,"last_share":1425986442,"hw_errors":0,"shares":0}],"serial":"8D7021745355"},"ttyACM5":{"chips":[{"autotune":1,"frequency":1028,"accepted":0,"hashrate":0,"rejected":0,"last_share":1425986442,"hw_errors":0,"shares":0},{"autotune":1,"frequency":1028,"accepted":0,"hashrate":0,"rejected":0,"last_share":1425986442,"hw_errors":0,"shares":0},{"autotune":1,"frequency":1028,"accepted":0,"hashrate":0,"rejected":0,"last_share":1425986442,"hw_errors":0,"shares":0},{"autotune":1,"frequency":1028,"accepted":0,"hashrate":0,"rejected":0,"last_share":1425986442,"hw_errors":0,"shares":0},{"autotune":1,"frequency":1028,"accepted":0,"hashrate":0,"rejected":0,"last_share":1425986442,"hw_errors":0,"shares":0}],"serial":"8D7623AA4951"},"ttyACM4":{"chips":[{"autotune":1,"frequency":1028,"accepted":1,"hashrate":86846,"rejected":0,"last_share":1425986875,"hw_errors":0,"shares":384},{"autotune":1,"frequency":1028,"accepted":1,"hashrate":86875,"rejected":0,"last_share":1425986506,"hw_errors":0,"shares":384},{"autotune":1,"frequency":1028,"accepted":4,"hashrate":86790,"rejected":0,"last_share":1425987073,"hw_errors":0,"shares":1536},{"autotune":1,"frequency":1028,"accepted":1,"hashrate":86818,"rejected":0,"last_share":1425986673,"hw_errors":0,"shares":384},{"autotune":1,"frequency":1028,"accepted":1,"hashrate":86863,"rejected":0,"last_share":1425986762,"hw_errors":0,"shares":384}],"serial":"8D7628895748"},"ttyACM3":{"chips":[{"autotune":1,"frequency":1028,"accepted":0,"hashrate":0,"rejected":0,"last_share":1425986442,"hw_errors":0,"shares":0},{"autotune":1,"frequency":1028,"accepted":0,"hashrate":0,"rejected":0,"last_share":1425986442,"hw_errors":0,"shares":0},{"autotune":1,"frequency":1028,"accepted":0,"hashrate":0,"rejected":0,"last_share":1425986442,"hw_errors":0,"shares":0},{"autotune":1,"frequency":1003,"accepted":0,"hashrate":0,"rejected":0,"last_share":1425986442,"hw_errors":2,"shares":0},{"autotune":1,"frequency":1028,"accepted":0,"hashrate":0,"rejected":0,"last_share":1425986442,"hw_errors":0,"shares":0}],"serial":"8D7122A75355"},"ttyACM2":{"chips":[{"autotune":1,"frequency":1028,"accepted":0,"hashrate":0,"rejected":0,"last_share":1425986442,"hw_errors":0,"shares":0},{"autotune":1,"frequency":1028,"accepted":0,"hashrate":0,"rejected":0,"last_share":1425986442,"hw_errors":1,"shares":0},{"autotune":1,"frequency":1028,"accepted":0,"hashrate":0,"rejected":0,"last_share":1425986442,"hw_errors":0,"shares":0},{"autotune":1,"frequency":1028,"accepted":1,"hashrate":57935,"rejected":0,"last_share":1425986682,"hw_errors":1,"shares":384},{"autotune":1,"frequency":1028,"accepted":0,"hashrate":0,"rejected":0,"last_share":1425986442,"hw_errors":0,"shares":0}],"serial":"6D7620874857"},"ttyACM1":{"chips":[{"autotune":1,"frequency":1028,"accepted":0,"hashrate":0,"rejected":0,"last_share":1425986443,"hw_errors":0,"shares":0},{"autotune":1,"frequency":1028,"accepted":0,"hashrate":0,"rejected":0,"last_share":1425986443,"hw_errors":0,"shares":0},{"autotune":1,"frequency":1028,"accepted":0,"hashrate":0,"rejected":0,"last_share":1425986443,"hw_errors":1,"shares":0},{"autotune":1,"frequency":1028,"accepted":0,"hashrate":0,"rejected":0,"last_share":1425986443,"hw_errors":0,"shares":0},{"autotune":1,"frequency":1028,"accepted":0,"hashrate":0,"rejected":0,"last_share":1425986443,"hw_errors":0,"shares":0}],"serial":"6D8733684853"},"ttyACM0":{"chips":[{"autotune":1,"frequency":1028,"accepted":4,"hashrate":86872,"rejected":0,"last_share":1425986974,"hw_errors":0,"shares":1536},{"autotune":1,"frequency":1028,"accepted":1,"hashrate":86872,"rejected":0,"last_share":1425986994,"hw_errors":0,"shares":384},{"autotune":1,"frequency":1028,"accepted":1,"hashrate":84853,"rejected":0,"last_share":1425986654,"hw_errors":0,"shares":384},{"autotune":1,"frequency":1028,"accepted":1,"hashrate":86793,"rejected":0,"last_share":1425986537,"hw_errors":0,"shares":384},{"autotune":1,"frequency":1028,"accepted":1,"hashrate":86214,"rejected":0,"last_share":1425986656,"hw_errors":0,"shares":384}],"serial":"6D8647A04853"}},"pools":[{"priority":0,"url":"stratum+tcp://us-east.multipool.us:7777","active":1,"user":"xx","pass":"x","stats":[{"start_time":1425986442,"shares":16128,"accepted":42,"stop_time":0,"rejected":0,"stats_id":1}],"stats_id":1},{"priority":1,"url":"stratum+tcp://us-west.multipool.us:7777","active":0,"user":"xxxx","pass":"x","stats":[],"stats_id":0},{"priority":2,"url":"stratum+tcp://us.clevermining.com:3333","active":0,"user":"xxxx","pass":"x","stats":[],"stats_id":0}],"start_time":1425986442,"err":0}`

I have 10 USB ASIC gridseed devices plugged in right now

**Comment by computeronix** [comment]
Looks like the fields to match in agent.py are

`total hash` (we may want to rename this and widget to Pool Hash Rate) -> sum of `4th` column (`hashrate`)

`accepted` -> sum of `3rd` column (`accepted`)

`rejected`-> sum of 5th column (`rejected`)

`errors` -> sum of 7th column (`hw_error`)

`elapsed` -> 8th column - last line (`start_time`)

**Comment by computeronix** [comment]
I think i was able to get it parsed.  Here is the code so far, now I am just lumping it together :)

`
        minerd_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        minerd_socket.connect((settings.get('minerd-address'), settings.get('minerd-port')))
        minerd_socket.sendall('{"get":"stats"}\n')
        received_data = minerd_socket.recv(8192)

        summary = json.loads(received_data.replace("\'", '"'))

        print summary

`

Output is (which is now JSON format :)
`

{u'pools': [{u'stats': [{u'stats_id': 1, u'start_time': 1426028146, u'rejected': 0, u'shares': 49920, u'stop_time': 1426028146, u'accepted': 130}], u'url': u'stratum+tcp://us-east.multipool.us:7777', u'priority': 0, u'user': u'gocloudmine.bulldozer', u'pass': u'x', u'active': 1, u'stats_id': 1}, {u'stats': [], u'url': u'stratum+tcp://us-west.multipool.us:7777', u'priority': 1, u'user': u'gocloudmine.bulldozer', u'pass': u'x', u'active': 0, u'stats_id': 0}, {u'stats': [], u'url': u'stratum+tcp://us.clevermining.com:3333', u'priority': 2, u'user': u'daffe7f89e0770ea90af773a0cebae2eaace73e2', u'pass': u'384', u'active': 0, u'stats_id': 0}], u'start_time': 1426028114, u'err': 0, u'devices': {u'ttyACM1': {u'serial': u'6D8733684853', u'chips': [{u'hw_errors': 0, u'rejected': 0, u'autotune': 1, u'frequency': 1163, u'shares': 0, u'last_share': 1426028115, u'accepted': 0, u'hashrate': 0}, {u'hw_errors': 0, u'rejected': 0, u'autotune': 1, u'frequency': 1163, u'shares': 0, u'last_share': 1426028115, u'accepted': 0, u'hashrate': 0}, {u'hw_errors': 0, u'rejected': 0, u'autotune': 1, u'frequency': 1163, u'shares': 0, u'last_share': 1426028115, u'accepted': 0, u'hashrate': 0}, {u'hw_errors': 2, u'rejected': 0, u'autotune': 1, u'frequency': 1138, u'shares': 0, u'last_share': 1426028115, u'accepted': 0, u'hashrate': 0}, {u'hw_errors': 7, u'rejected': 0, u'autotune': 1, u'frequency': 1088, u'shares': 0, u'last_share': 1426028115, u'accepted': 0, u'hashrate': 0}]}, u'ttyACM0': {u'serial': u'6D8647A04853', u'chips': [{u'hw_errors': 0, u'rejected': 0, u'autotune': 1, u'frequency': 1163, u'shares': 2688, u'last_share': 1426029801, u'accepted': 7, u'hashrate': 98494}, {u'hw_errors': 0, u'rejected': 0, u'autotune': 1, u'frequency': 1163, u'shares': 1536, u'last_share': 1426029807, u'accepted': 4, u'hashrate': 98477}, {u'hw_errors': 0, u'rejected': 0, u'autotune': 1, u'frequency': 1163, u'shares': 3072, u'last_share': 1426029735, u'accepted': 8, u'hashrate': 98470}, {u'hw_errors': 0, u'rejected': 0, u'autotune': 1, u'frequency': 1163, u'shares': 2688, u'last_share': 1426029355, u'accepted': 7, u'hashrate': 98460}, {u'hw_errors': 0, u'rejected': 0, u'autotune': 1, u'frequency': 1188, u'shares': 4224, u'last_share': 1426029692, u'accepted': 11, u'hashrate': 98432}]}, u'ttyACM3': {u'serial': u'8D7122A75355', u'chips': [{u'hw_errors': 0, u'rejected': 0, u'autotune': 1, u'frequency': 1163, u'shares': 0, u'last_share': 1426028115, u'accepted': 0, u'hashrate': 0}, {u'hw_errors': 0, u'rejected': 0, u'autotune': 1, u'frequency': 1163, u'shares': 0, u'last_share': 1426028115, u'accepted': 0, u'hashrate': 0}, {u'hw_errors': 0, u'rejected': 0, u'autotune': 1, u'frequency': 1163, u'shares': 0, u'last_share': 1426028115, u'accepted': 0, u'hashrate': 0}, {u'hw_errors': 3, u'rejected': 0, u'autotune': 1, u'frequency': 1138, u'shares': 0, u'last_share': 1426028115, u'accepted': 0, u'hashrate': 0}, {u'hw_errors': 0, u'rejected': 0, u'autotune': 1, u'frequency': 1163, u'shares': 0, u'last_share': 1426028115, u'accepted': 0, u'hashrate': 0}]}, u'ttyACM2': {u'serial': u'6D7620874857', u'chips': [{u'hw_errors': 4, u'rejected': 0, u'autotune': 1, u'frequency': 1113, u'shares': 0, u'last_share': 1426028115, u'accepted': 0, u'hashrate': 0}, {u'hw_errors': 3, u'rejected': 0, u'autotune': 1, u'frequency': 1138, u'shares': 0, u'last_share': 1426028115, u'accepted': 0, u'hashrate': 0}, {u'hw_errors': 2, u'rejected': 0, u'autotune': 1, u'frequency': 1138, u'shares': 0, u'last_share': 1426028115, u'accepted': 0, u'hashrate': 0}, {u'hw_errors': 2, u'rejected': 0, u'autotune': 1, u'frequency': 1138, u'shares': 0, u'last_share': 1426028115, u'accepted': 0, u'hashrate': 0}, {u'hw_errors': 1, u'rejected': 0, u'autotune': 1, u'frequency': 1163, u'shares': 768, u'last_share': 1426028891, u'accepted': 2, u'hashrate': 59128}]}, u'ttyACM5': {u'serial': u'8D7623AA4951', u'chips': [{u'hw_errors': 0, u'rejected': 0, u'autotune': 1, u'frequency': 1163, u'shares': 0, u'last_share': 1426028115, u'accepted': 0, u'hashrate': 0}, {u'hw_errors': 0, u'rejected': 0, u'autotune': 1, u'frequency': 1163, u'shares': 0, u'last_share': 1426028115, u'accepted': 0, u'hashrate': 0}, {u'hw_errors': 0, u'rejected': 0, u'autotune': 1, u'frequency': 1163, u'shares': 0, u'last_share': 1426028115, u'accepted': 0, u'hashrate': 0}, {u'hw_errors': 0, u'rejected': 0, u'autotune': 1, u'frequency': 1163, u'shares': 0, u'last_share': 1426028115, u'accepted': 0, u'hashrate': 0}, {u'hw_errors': 0, u'rejected': 0, u'autotune': 1, u'frequency': 1163, u'shares': 0, u'last_share': 1426028115, u'accepted': 0, u'hashrate': 0}]}, u'ttyACM4': {u'serial': u'8D7628895748', u'chips': [{u'hw_errors': 1, u'rejected': 0, u'autotune': 1, u'frequency': 1163, u'shares': 2688, u'last_share': 1426029670, u'accepted': 7, u'hashrate': 92254}, {u'hw_errors': 0, u'rejected': 0, u'autotune': 1, u'frequency': 1163, u'shares': 1920, u'last_share': 1426029605, u'accepted': 5, u'hashrate': 98397}, {u'hw_errors': 0, u'rejected': 0, u'autotune': 1, u'frequency': 1163, u'shares': 1920, u'last_share': 1426029815, u'accepted': 5, u'hashrate': 98436}, {u'hw_errors': 0, u'rejected': 0, u'autotune': 1, u'frequency': 1163, u'shares': 3456, u'last_share': 1426029809, u'accepted': 9, u'hashrate': 98472}, {u'hw_errors': 0, u'rejected': 0, u'autotune': 1, u'frequency': 1163, u'shares': 3456, u'last_share': 1426029665, u'accepted': 9, u'hashrate': 98426}]}, u'ttyACM7': {u'serial': u'6D84556F4853', u'chips': [{u'hw_errors': 0, u'rejected': 0, u'autotune': 1, u'frequency': 1163, u'shares': 1920, u'last_share': 1426029715, u'accepted': 5, u'hashrate': 98472}, {u'hw_errors': 0, u'rejected': 0, u'autotune': 1, u'frequency': 1163, u'shares': 1920, u'last_share': 1426029232, u'accepted': 5, u'hashrate': 98432}, {u'hw_errors': 0, u'rejected': 0, u'autotune': 1, u'frequency': 1163, u'shares': 1536, u'last_share': 1426029727, u'accepted': 4, u'hashrate': 98498}, {u'hw_errors': 0, u'rejected': 0, u'autotune': 1, u'frequency': 1163, u'shares': 1920, u'last_share': 1426029777, u'accepted': 5, u'hashrate': 98484}, {u'hw_errors': 0, u'rejected': 0, u'autotune': 1, u'frequency': 1163, u'shares': 2688, u'last_share': 1426029484, u'accepted': 7, u'hashrate': 98478}]}, u'ttyACM6': {u'serial': u'8D7021745355', u'chips': [{u'hw_errors': 0, u'rejected': 0, u'autotune': 1, u'frequency': 1163, u'shares': 0, u'last_share': 1426028115, u'accepted': 0, u'hashrate': 0}, {u'hw_errors': 0, u'rejected': 0, u'autotune': 1, u'frequency': 1163, u'shares': 0, u'last_share': 1426028115, u'accepted': 0, u'hashrate': 0}, {u'hw_errors': 0, u'rejected': 0, u'autotune': 1, u'frequency': 1163, u'shares': 0, u'last_share': 1426028115, u'accepted': 0, u'hashrate': 0}, {u'hw_errors': 0, u'rejected': 0, u'autotune': 1, u'frequency': 1163, u'shares': 0, u'last_share': 1426028115, u'accepted': 0, u'hashrate': 0}, {u'hw_errors': 0, u'rejected': 0, u'autotune': 1, u'frequency': 1163, u'shares': 0, u'last_share': 1426028115, u'accepted': 0, u'hashrate': 0}]}, u'ttyACM9': {u'serial': u'6D86437A5157', u'chips': [{u'hw_errors': 2, u'rejected': 0, u'autotune': 1, u'frequency': 1138, u'shares': 384, u'last_share': 1426028984, u'accepted': 1, u'hashrate': 48343}, {u'hw_errors': 6, u'rejected': 0, u'autotune': 1, u'frequency': 1088, u'shares': 0, u'last_share': 1426028114, u'accepted': 0, u'hashrate': 0}, {u'hw_errors': 0, u'rejected': 0, u'autotune': 1, u'frequency': 1163, u'shares': 0, u'last_share': 1426028114, u'accepted': 0, u'hashrate': 0}, {u'hw_errors': 0, u'rejected': 0, u'autotune': 1, u'frequency': 1163, u'shares': 0, u'last_share': 1426028114, u'accepted': 0, u'hashrate': 0}, {u'hw_errors': 5, u'rejected': 0, u'autotune': 1, u'frequency': 1113, u'shares': 0, u'last_share': 1426028114, u'accepted': 0, u'hashrate': 0}]}, u'ttyACM8': {u'serial': u'8D7052755355', u'chips': [{u'hw_errors': 0, u'rejected': 0, u'autotune': 1, u'frequency': 1163, u'shares': 1536, u'last_share': 1426029799, u'accepted': 4, u'hashrate': 98463}, {u'hw_errors': 0, u'rejected': 0, u'autotune': 1, u'frequency': 1163, u'shares': 1920, u'last_share': 1426028991, u'accepted': 5, u'hashrate': 98338}, {u'hw_errors': 0, u'rejected': 0, u'autotune': 1, u'frequency': 1163, u'shares': 2304, u'last_share': 1426029429, u'accepted': 6, u'hashrate': 98456}, {u'hw_errors': 0, u'rejected': 0, u'autotune': 1, u'frequency': 1163, u'shares': 2304, u'last_share': 1426029567, u'accepted': 6, u'hashrate': 98481}, {u'hw_errors': 0, u'rejected': 0, u'autotune': 1, u'frequency': 1163, u'shares': 3072, u'last_share': 1426029810, u'accepted': 8, u'hashrate': 98436}]}}}
`

I will work on matching this up as I get time.  This is good news, can now support cpuminer :)
`

**Comment by computeronix** [comment]
updated the code to support cpuminer
